collections:
  - name: "gallery"
    label: "Artwork"
    folder: "src/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Created Date", name: "date_created", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Published Date", name: "published", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "markdown"}
      - {label: "Main Image", name: "src", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Gallery Groups", name: "gallery", widget: "list"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Social Image", name: "og_image", widget: "image"}
      - {label: "Social Image Alt Text", name: "og_image_alt", widget: "string"}

  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published Date", name: "published", widget: "datetime", format: "YYYY-MM-DD"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Main Image", name: "src", widget: "image"}
      - {label: "Alt Text", name: "alt", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Display in Gallery", name: "displayInGallery", widget: "boolean", default: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Social Image", name: "og_image", widget: "image"}
      - {label: "Social Image Alt Text", name: "og_image_alt", widget: "string"}